# Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.datasets import load_iris

# Uploading the Data

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving iris_tidy.csv to iris_tidy (3).csv


# Reading the Data

In [ ]:
import pandas as pd

# Assuming 'iris_tidy.csv' is in the same directory as your notebook
data = pd.read_csv('iris_tidy.csv')

# Display the first few rows to check if it loaded correctly
print(data.head())

   Unnamed: 0 Species   Part Measure  Value
0           1  setosa  Sepal  Length    5.1
1           2  setosa  Sepal  Length    4.9
2           3  setosa  Sepal  Length    4.7
3           4  setosa  Sepal  Length    4.6
4           5  setosa  Sepal  Length    5.0


# Split the Dataset into training and testing sets

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=42)

# Perform LDA

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)
y_pred = lda.predict(X_test)

# Evaluate the Model

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

In [ ]:
print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{class_report}")

Accuracy: 1.0
Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

